name: CI

on:
  push:
    branches: [master]
  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, windows-2022]
        method: [local, network]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

      - name: Run the action on this runner with method ${{matrix.method}}
        uses: ./
        with:
          method: ${{matrix.method}}

      - name: Run the action on this runner with nvcc subpackage only
        id: test-action
        uses: ./
        with:
          method: ${{matrix.method}}
          sub-packages: '["nvcc"]'

      - name: Print output cuda version
        run: echo "${{ steps.test-action.outputs.cuda }}"

      - name: Print output CUDA_PATH
        run: echo "${{ steps.test-action.outputs.CUDA_PATH }}"

      - name: Test if nvcc is available
        run: nvcc -V

      - name: List paths
        shell: powershell
        run: |
          ls $env:CUDA_PATH
          ls $env:CUDA_PATH\bin
          ls $env:CUDA_PATH\include
